branches:
  except:
    - travis

language: java

jdk:
- openjdk8
#- openjdk10
#- openjdk11
#- openjdk12  

env:
- BUILD_TYPE=snapshot/$TRAVIS_BRANCH

before_install:
- docker run -d -e SA_PASSWORD=5F4Dt9ky9dU$ -e SQLSERVER_DATABASE=sc -e SQLSERVER_USER=user -e SQLSERVER_PASSWORD=5F4Dt9ky9dU$ -p 1433:1433 exoplatform/sqlserver:2017-CU8
- docker run -d -e POSTGRES_PASSWORD=5F4Dt9ky9dU$ -p 5432:5432 postgres:12.1
- docker run -d -e MYSQL_ROOT_PASSWORD=5F4Dt9ky9dU$ -e MYSQL_DATABASE=sc -p 3306:3306 mysql:8.0.19
- docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" paulcwarren/elasticsearch:7.6.2
- docker run -d -p 8983:8983 paulcwarren/solr solr-precreate solr

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
 - mvn -P tests install jacoco:report -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
   
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: 1.2.x
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      tags: true
